openapi: 3.0.3
info:
  title: Frontend Integrated API Schema
  version: 1.0.0
  description: API schema used by React client. Paths reflect server implementation.
paths:
  /api/hello/:
    get:
      summary: Hello message
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  timestamp:
                    type: string
                    format: date-time
  /api/auth/register/:
    post:
      summary: Register new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                email:
                  type: string
              required: [username, password]
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  access:
                    type: string
                  refresh:
                    type: string
                  user:
                    type: object
                    properties:
                      id: { type: integer }
                      username: { type: string }
                      role: { type: string }
                      date_joined: { type: string, format: date-time }
  /api/auth/login/:
    post:
      summary: Login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required: [username, password]
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  access:
                    type: string
                  refresh:
                    type: string
                  user:
                    type: object
                    properties:
                      id: { type: integer }
                      username: { type: string }
                      role: { type: string }
                      date_joined: { type: string, format: date-time }
  /api/auth/me/:
    get:
      summary: Get current user
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id: { type: integer }
                  username: { type: string }
                  role: { type: string }
                  date_joined: { type: string, format: date-time }
        '401':
          description: Unauthorized
  /api/chat/messages/:
    get:
      summary: List chat messages
      security:
        - bearerAuth: []
      parameters:
        - name: limit
          in: query
          schema: { type: integer }
        - name: after_id
          in: query
          schema: { type: integer }
        - name: after_ts
          in: query
          schema: { type: string, format: date-time }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ChatMessage'
    post:
      summary: Create message
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
              required: [content]
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatMessage'
  /api/chat/messages/{id}/:
    delete:
      summary: Delete message (admin/moderator)
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: integer }
      responses:
        '204':
          description: No Content
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    ChatMessage:
      type: object
      properties:
        id: { type: integer }
        content: { type: string }
        created_at: { type: string, format: date-time }
        author:
          type: object
          properties:
            id: { type: integer }
            username: { type: string }
            role: { type: string }
